# Generated by Django 4.2.25 on 2025-10-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturevideo',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='lecturevideo',
            name='transcription_status',
        ),
        migrations.AddField(
            model_name='lecturevideo',
            name='quiz_questions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturevideo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='lecturevideo',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturevideo',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
