# Generated by Django 5.2.7 on 2025-10-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_lecturevideo_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturevideo',
            name='transcription_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='lecturevideo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=50),
        ),
    ]
