# ============================
#  CELERY WORKER DOCKERFILE
# ============================

FROM python:3.10-bullseye

WORKDIR /app

# Copy backend requirements file first
COPY ./backend/requirements.txt .

# Install dependencies
RUN pip install --upgrade pip setuptools wheel && \
    pip install -r requirements.txt && \
    pip install whitenoise

# Copy all backend source code
COPY ./backend/ .

# Run Celery worker
CMD ["celery", "-A", "core", "worker", "--loglevel=info"]
